
package test;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import test.clases.Cajero;
import test.clases.CuentaDebito;

/**
 *
 * @author jarug
 */
public class Retiro extends javax.swing.JFrame {
    double saldoActual;
    CuentaDebito cuentaDe;
    String numCuenta;
    /**
     * Creates new form Retiro
     */
    
    
    
    public Retiro(String numCuenta) throws ClassNotFoundException {
        initComponents();
        
        this.numCuenta = numCuenta;
        this.cuentaDe = new CuentaDebito(numCuenta);
        this.saldoActual = cuentaDe.getSaldo(numCuenta);
        etiquetaSaldo.setText(String.valueOf(saldoActual));
    }

    Retiro(Principal aThis, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        etiquetaSaldo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cantidadRetiroTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        botonRetiro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(250, 150));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Saldo actual");

        etiquetaSaldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        etiquetaSaldo.setText("$...");
        etiquetaSaldo.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("Cantidad a retirar");

        cantidadRetiroTF.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("$");

        botonRetiro.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        botonRetiro.setText("Retirar");
        botonRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRetiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cantidadRetiroTF)
                    .addComponent(etiquetaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(botonRetiro)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(etiquetaSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cantidadRetiroTF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(botonRetiro)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRetiroActionPerformed
        // TODO add your handling code here:
        double cantidadRetiro=0;
        
        
        //etiquetaSaldo.setText(String.valueOf(saldoActual));
        cantidadRetiro = Double.parseDouble(cantidadRetiroTF.getText());
        
        if (cantidadRetiro > saldoActual){
            JOptionPane.showMessageDialog(null, "El saldo en la cuenta no es suficiente", "Alerta", JOptionPane.ERROR_MESSAGE); 
        }else{
            if(cantidadRetiro<100){
                JOptionPane.showMessageDialog(null, "La cantidad mínima para retirar es de $100", "Alerta", JOptionPane.ERROR_MESSAGE);
                System.exit(0);
            }else{
            Cajero caj = new Cajero(1);
                try {
                    caj.retirarEfectivo(numCuenta, cantidadRetiro);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Retiro.class.getName()).log(Level.SEVERE, null, ex);
                }
            } 

        }
        
    }//GEN-LAST:event_botonRetiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Retiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRetiro;
    private javax.swing.JTextField cantidadRetiroTF;
    private javax.swing.JLabel etiquetaSaldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
